In [1]:
import numpy as np
import pandas as pd


In [5]:
!pip install opendatasets


In [6]:
import opendatasets as od

od.download('https://www.kaggle.com/datasets/abhi8923shriv/sentiment-analysis-dataset?select=training.1600000.processed.noemoticon.csv')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: ANANDRAJ012
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/abhi8923shriv/sentiment-analysis-dataset


100%|██████████| 54.4M/54.4M [00:00<00:00, 152MB/s]


In [3]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
df1=pd.read_csv('sentiment-analysis-dataset/test.csv',encoding='latin1')
df2=pd.read_csv('sentiment-analysis-dataset/train.csv',encoding='latin1')

In [8]:
df1.head()

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0


In [10]:
df=pd.concat([df1,df2])


In [11]:
df.drop(columns=['Age of User','Population -2020','Land Area (Km²)','Density (P/Km²)','Time of Tweet','Country','selected_text','textID'],inplace=True)

In [12]:
df.head()

,text,sentiment
0,Last session of the day http://twitpic.com/67ezh,neutral
1,Shanghai is also really exciting (precisely -...,positive
2,"Recession hit Veronique Branquinho, she has to...",negative
3,happy bday!,positive
4,http://twitpic.com/4w75p - I like it!!,positive


In [13]:
df.dropna(inplace=True)

In [14]:
df.duplicated().sum()

0

# Tag removal


In [15]:
import re

In [16]:
df['cleaned']=df['text'].apply(lambda x:str(x).lower())

In [17]:
df.head()

,text,sentiment,cleaned
0,Last session of the day http://twitpic.com/67ezh,neutral,last session of the day http://twitpic.com/67ezh
1,Shanghai is also really exciting (precisely -...,positive,shanghai is also really exciting (precisely -...
2,"Recession hit Veronique Branquinho, she has to...",negative,"recession hit veronique branquinho, she has to..."
3,happy bday!,positive,happy bday!
4,http://twitpic.com/4w75p - I like it!!,positive,http://twitpic.com/4w75p - i like it!!


In [18]:
def rem_tag(text):
    cleaned_text = re.sub(re.compile('<*?.>'),'',str(text))

    return cleaned_text

In [19]:
df['cleaned'] = df['cleaned'].apply(rem_tag)

In [20]:
df.head()

,text,sentiment,cleaned
0,Last session of the day http://twitpic.com/67ezh,neutral,last session of the day http://twitpic.com/67ezh
1,Shanghai is also really exciting (precisely -...,positive,shanghai is also really exciting (precisely -...
2,"Recession hit Veronique Branquinho, she has to...",negative,"recession hit veronique branquinho, she has to..."
3,happy bday!,positive,happy bday!
4,http://twitpic.com/4w75p - I like it!!,positive,http://twitpic.com/4w75p - i like it!!


In [21]:
def rem_char(text):
    text = re.sub(re.compile('<a-zA-Z0-9\s>'),'',str(text))
    text = re.sub(r'\s',' ',str(text)).strip()

    return text

In [22]:
df['cleaned'] = df['cleaned'].apply(rem_char)

df.head()

,text,sentiment,cleaned
0,Last session of the day http://twitpic.com/67ezh,neutral,last session of the day http://twitpic.com/67ezh
1,Shanghai is also really exciting (precisely -...,positive,shanghai is also really exciting (precisely --...
2,"Recession hit Veronique Branquinho, she has to...",negative,"recession hit veronique branquinho, she has to..."
3,happy bday!,positive,happy bday!
4,http://twitpic.com/4w75p - I like it!!,positive,http://twitpic.com/4w75p - i like it!!


In [23]:
def normalize(text):
    if isinstance(text,str):
        text = re.sub(r'[^\w\s]',"",text)
        text = re.sub(r"\s+",' ', text).strip()
    else:
        text = str(text)

    return text

df['cleaned'] = df['cleaned'].apply(normalize)



In [24]:
df.head()

,text,sentiment,cleaned
0,Last session of the day http://twitpic.com/67ezh,neutral,last session of the day httptwitpiccom67ezh
1,Shanghai is also really exciting (precisely -...,positive,shanghai is also really exciting precisely sky...
2,"Recession hit Veronique Branquinho, she has to...",negative,recession hit veronique branquinho she has to ...
3,happy bday!,positive,happy bday
4,http://twitpic.com/4w75p - I like it!!,positive,httptwitpiccom4w75p i like it


In [27]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [28]:
stop_words = stopwords.words('english')
df['cleaned'] = df['cleaned'].apply(lambda x:[i for i in x.split() if i not in stop_words]).apply(lambda x:" ".join(x))

In [ ]:
df.head()

,text,sentiment,cleaned
0,Last session of the day http://twitpic.com/67ezh,neutral,last session day httptwitpiccom67ezh
1,Shanghai is also really exciting (precisely -...,positive,shanghai also really exciting precisely skyscr...
2,"Recession hit Veronique Branquinho, she has to...",negative,recession hit veronique branquinho quit compan...
3,happy bday!,positive,happy bday
4,http://twitpic.com/4w75p - I like it!!,positive,httptwitpiccom4w75p like


In [29]:
def remove_urls(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    pattern = re.compile(r'http?://\S+|www\.\S+')
    return pattern.sub(r'',text)


In [30]:
df['cleaned'] = df['text'].apply(remove_urls)

In [31]:
df['cleaned'] = df['cleaned'].apply(lambda x:[i for i in x.split() if i not in stop_words]).apply(lambda x:" ".join(x))
df['cleaned'] = df['cleaned'].apply(normalize)
df['cleaned'] = df['cleaned'].apply(rem_char)
df['cleaned'] = df['cleaned'].apply(rem_tag)

In [32]:
df['cleaned']=df['cleaned'].apply(lambda x:str(x).lower())

In [33]:
df.head()

,text,sentiment,cleaned
0,Last session of the day http://twitpic.com/67ezh,neutral,last session day
1,Shanghai is also really exciting (precisely -...,positive,shanghai also really exciting precisely skyscr...
2,"Recession hit Veronique Branquinho, she has to...",negative,recession hit veronique branquinho quit compan...
3,happy bday!,positive,happy bday
4,http://twitpic.com/4w75p - I like it!!,positive,i like it


In [34]:
import string

a = string.punctuation

def remove_punctuation(text):
    return text.translate(str.maketrans('','',a))

In [35]:
df['cleaned'] = df['cleaned'].apply(remove_punctuation)

In [36]:
df.head()

,text,sentiment,cleaned
0,Last session of the day http://twitpic.com/67ezh,neutral,last session day
1,Shanghai is also really exciting (precisely -...,positive,shanghai also really exciting precisely skyscr...
2,"Recession hit Veronique Branquinho, she has to...",negative,recession hit veronique branquinho quit compan...
3,happy bday!,positive,happy bday
4,http://twitpic.com/4w75p - I like it!!,positive,i like it


In [37]:
X= df['cleaned']
y = df['sentiment']



In [38]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=13)

In [40]:
cv = CountVectorizer()

In [48]:
  X_train_processed= cv.fit_transform(X_train).toarray()
  X_test_processed = cv.transform(X_test).toarray()

# Model building

In [49]:
from sklearn.ensemble import RandomForestClassifier


rf = RandomForestClassifier()
rf.fit(X_train_processed,y_train)

RandomForestClassifier()

In [50]:
print("Training Data Shape:", X_train_processed.shape)
print("Test Data Shape:", X_test_processed.shape)


Training Data Shape: (24811, 26077)
Test Data Shape: (6203, 26077)


In [52]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = rf.predict(X_test_processed)

# performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.6946638723198453

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.60      0.65      1768
           1       0.64      0.74      0.69      2492
           2       0.75      0.73      0.74      1943

    accuracy                           0.69      6203
   macro avg       0.71      0.69      0.69      6203
weighted avg       0.70      0.69      0.69      6203


Confusion Matrix:
 [[1055  594  119]
 [ 308 1839  345]
 [  94  434 1415]]
